export const dishSuggestions = [
  'Chicken Biryani',
  'Paneer Butter Masala',
  'Egg Curry',
  'Dal Tadka',
  'Rajma Chawal',
  'Aloo Paratha',
  'Chole Bhature',
  'Pasta',
  'Pizza',
  'Burger',
  'Salad',
  'Grilled Chicken',
  'Fish Curry',
  'Veg Pulao',
  'Dosa',
  'Idli',
  'Sambar',
  'Upma',
  'Poha',
  'Omelette',
  'Fried Rice',
  'Noodles',
  'Soup',
  'Sandwich',
  'Cheese Toast',
  'Tomato Soup',
  'Chicken Curry',
  'Beef Stir Fry',
  'Pasta with Tomato Sauce',
  'Mixed Green Salad',
  'Rice and Beans',
  'Vegetable Curry',
  'Butter Chicken',
  'Palak Paneer',
  'Mutton Rogan Josh',
  'Kadhi Chawal',
  'Chicken Tikka',
  'Veg Sandwich',
  'Fruit Bowl',
  'Oats Porridge',
  'Pancakes',
  'Waffles',
  'French Toast',
  'Scrambled Eggs',
  'Tofu Stir Fry',
  'Quinoa Salad',
  'Caesar Salad',
  'Greek Salad',
  'Chicken Caesar Wrap',
  'Veggie Burger',
  'Falafel',
  'Shawarma',
  'Burrito',
  'Tacos',
  'Sushi',
  'Ramen',
  'Pho',
  'Spring Rolls',
  'Miso Soup',
  'Kimchi',
  'Bibimbap',
  'Pad Thai',
  'Green Curry',
  'Red Curry',
  'Tom Yum Soup',
  'Chicken Satay',
  'Lentil Soup',
  'Pumpkin Soup',
  'Minestrone',
  'Lasagna',
  'Spaghetti',
  'Mac and Cheese',
  'Risotto',
  'Paella',
  'Gnocchi',
  'Bruschetta',
  'Caprese Salad',
  'Frittata',
  'Shakshuka',
  'Avocado Toast',
  'Granola Bowl',
  'Smoothie',
  'Protein Shake',
  'Energy Bar',
  'Chicken Soup',
  'Vegetable Soup',
  'Cornflakes',
  'Muesli',
  'Porridge',
  'Milkshake',
  'Ice Cream',
  'Brownie',
  'Cupcake',
  'Muffin',
  'Chocolate Cake',
  'Fruit Salad',
  'Apple Pie',
  'Banana Bread',
  'Carrot Cake',
  'Lemon Tart',
  'Cheesecake',
  'Gulab Jamun',
  'Rasgulla',
  'Jalebi',
  'Kheer',
  'Halwa',
  'Barfi',
  'Ladoo',
  'Peda',
  'Sandesh',
  'Rabri',
  'Malpua',
  'Modak',
  'Sheera',
  'Payasam',
  'Basundi',
  'Shrikhand',
  'Phirni',
  'Kulfi',
  'Ice Gola',
  'Falooda',
  'Samosa',
  'Pakora',
  'Bhajiya',
  'Vada Pav',
  'Dabeli',
  'Kachori',
  'Bhel Puri',
  'Pani Puri',
  'Sev Puri',
  'Dhokla',
  'Handwo',
  'Thepla',
  'Undhiyu',
  'Patra',
  'Khandvi',
  'Fafda',
  'Chakli',
  'Murukku',
  'Appam',
  'Puttu',
  'Idiyappam',
  'Neer Dosa',
  'Akki Roti',
  'Ragi Mudde',
  'Bisi Bele Bath',
  'Mysore Pak',
  'Obbattu',
  'Kesari Bath',
  'Rava Dosa',
  'Set Dosa',
  'Bonda',
  'Maddur Vada',
  'Chitranna',
  'Puliyogare',
  'Vangi Bath',
  'Kharabath',
  'Sagu',
  'Kosambari',
  'Avial',
  'Thoran',
  'Olan',
  'Kaalan',
  'Erissery',
  'Pachadi',
  'Kootu',
  'Poriyal',
  'Sambar Rice',
  'Curd Rice',
  'Lemon Rice',
  'Tamarind Rice',
  'Coconut Rice',
  'Tomato Rice',
  'Jeera Rice',
  'Ghee Rice',
  'Peas Pulao',
  'Veg Biryani',
  'Chicken Biryani',
  'Mutton Biryani',
  'Fish Biryani',
  'Egg Biryani',
  'Paneer Biryani',
  'Veg Fried Rice',
  'Chicken Fried Rice',
  'Egg Fried Rice',
  'Prawn Fried Rice',
  'Schezwan Fried Rice',
  'Manchurian',
  'Gobi Manchurian',
  'Paneer Manchurian',
  'Chicken Manchurian',
  'Veg Hakka Noodles',
  'Chicken Hakka Noodles',
  'Egg Hakka Noodles',
  'Prawn Hakka Noodles',
  'Veg Chowmein',
  'Chicken Chowmein',
  'Egg Chowmein',
  'Prawn Chowmein',
  'Veg Spring Roll',
  'Chicken Spring Roll',
  'Egg Spring Roll',
  'Prawn Spring Roll',
  'Veg Momos',
  'Chicken Momos',
  'Paneer Momos',
  'Fried Momos',
  'Steamed Momos',
  'Tandoori Momos',
  'Veg Pizza',
  'Chicken Pizza',
  'Paneer Pizza',
  'Pepperoni Pizza',
  'Margherita Pizza',
  'Farmhouse Pizza',
  'Veggie Supreme Pizza',
  'Deluxe Veggie Pizza',
  'Chicken Supreme Pizza',
  'BBQ Chicken Pizza',
  'Cheese Burst Pizza',
  'Thin Crust Pizza',
  'Stuffed Crust Pizza',
  'Garlic Bread',
  'Cheese Garlic Bread',
  'Stuffed Garlic Bread',
  'Paneer Tikka',
  'Chicken Tikka',
  'Fish Tikka',
  'Seekh Kebab',
  'Shami Kebab',
  'Hara Bhara Kebab',
  'Galouti Kebab',
  'Mutton Kebab',
  'Chicken Kebab',
  'Paneer Kebab',
  'Veg Kebab',
  'Dahi Kebab',
  'Corn Kebab',
  'Aloo Tikki',
  'Ragda Pattice',
  'Pav Bhaji',
  'Misal Pav',
  'Usal Pav',
  'Sabudana Khichdi',
  'Sabudana Vada',
  'Batata Vada',
  'Kanda Poha',
  'Sheera',
  'Puran Poli',
  'Modak',
  'Shrikhand',
  'Basundi',
  'Kharvas',
  'Aliv Kheer',
  'Doodh Pak',
  'Satori',
  'Anarsa',
  'Chirote',
  'Karanji',
  'Laddu',
  'Barfi',
  'Peda',
  'Kalakand',
  'Milk Cake',
  'Rabdi',
  'Malpua',
  'Imarti',
  'Balushahi',
  'Chhena Poda',
  'Chhena Gaja',
  'Ras Malai',
  'Cham Cham',
  'Sandesh',
  'Kheer Kadam',
  'Pantua',
  'Langcha',
  'Nolen Gurer Sandesh',
  'Patishapta',
  'Pithe',
  'Bhapa Doi',
  'Payesh',
  'Sondesh',
  'Mihidana',
  'Sitabhog',
  'Jalbhara Sandesh',
  'Chomchom',
  'Kacha Golla',
  'Kalo Jam',
  'Ledikeni',
  'Malai Sandwich',
  'Malai Roll',
  'Malai Chop',
  'Rasgulla',
  'Gulab Jamun',
  'Kala Jamun',
  'Khoya Barfi',
  'Khoya Peda',
  'Khoya Laddu',
  'Khoya Gujiya',
  'Khoya Kheer',
  'Khoya Halwa',
  'Khoya Modak',
  'Khoya Malpua',
  'Khoya Rabdi',
  'Khoya Basundi',
  'Khoya Shrikhand',
  'Khoya Phirni',
  'Khoya Kulfi',
  'Khoya Ice Cream',
  'Khoya Falooda',
  'Khoya Gajar Halwa',
  'Khoya Lauki Halwa',
  'Khoya Dudhi Halwa',
  'Khoya Moong Dal Halwa',
  'Khoya Besan Halwa',
  'Khoya Badam Halwa',
  'Khoya Coconut Halwa',
  'Khoya Pineapple Halwa',
  'Khoya Mango Halwa',
  'Khoya Apple Halwa',
  'Khoya Banana Halwa',
  'Khoya Papaya Halwa',
  'Khoya Carrot Halwa',
  'Khoya Beetroot Halwa',
  'Khoya Pumpkin Halwa',
  'Khoya Sweet Potato Halwa',
  'Khoya Potato Halwa',
  'Khoya Yam Halwa',
  'Khoya Arbi Halwa',
  'Khoya Taro Halwa',
  'Khoya Colocasia Halwa',
  'Khoya Elephant Foot Yam Halwa',
  'Khoya Suran Halwa',
  'Khoya Zimikand Halwa',
  'Khoya Jimikand Halwa',
  'Khoya Oal Halwa',
  'Khoya Ol Halwa',
  'Khoya Oal ki Sabzi',
  'Khoya Ol ki Sabzi',
  'Khoya Oal Curry',
  'Khoya Ol Curry',
  'Khoya Oal Fry',
  'Khoya Ol Fry',
  'Khoya Oal Bharta',
  'Khoya Ol Bharta',
  'Khoya Oal Chokha',
  'Khoya Ol Chokha',
  'Khoya Oal Tikki',
  'Khoya Ol Tikki',
  'Khoya Oal Cutlet',
  'Khoya Ol Cutlet',
  'Khoya Oal Pakora',
  'Khoya Ol Pakora',
  'Khoya Oal Bhaji',
  'Khoya Ol Bhaji',
  'Khoya Oal Bhujia',
  'Khoya Ol Bhujia',
  'Khoya Oal Chips',
  'Khoya Ol Chips',
  'Khoya Oal Fries',
  'Khoya Ol Fries',
  'Khoya Oal Wafers',
  'Khoya Ol Wafers',
  'Khoya Oal Papad',
  'Khoya Ol Papad',
  'Khoya Oal Chutney',
  'Khoya Ol Chutney',
  'Khoya Oal Pickle',
  'Khoya Ol Pickle',
  'Khoya Oal Raita',
  'Khoya Ol Raita',
  'Khoya Oal Salad',
  'Khoya Ol Salad',
  'Khoya Oal Soup',
  'Khoya Ol Soup',
  'Khoya Oal Juice',
  'Khoya Ol Juice',
  'Khoya Oal Shake',
  'Khoya Ol Shake',
  'Khoya Oal Lassi',
  'Khoya Ol Lassi',
  'Khoya Oal Milkshake',
  'Khoya Ol Milkshake',
  'Khoya Oal Smoothie',
  'Khoya Ol Smoothie',
  'Khoya Oal Ice Cream',
  'Khoya Ol Ice Cream',
  'Khoya Oal Kulfi',
  'Khoya Ol Kulfi',
  'Khoya Oal Falooda',
  'Khoya Ol Falooda',
  'Khoya Oal Rabdi',
  'Khoya Ol Rabdi',
  'Khoya Oal Basundi',
  'Khoya Ol Basundi',
  'Khoya Oal Shrikhand',
  'Khoya Ol Shrikhand',
  'Khoya Oal Phirni',
  'Khoya Ol Phirni',
  'Khoya Oal Kheer',
  'Khoya Ol Kheer',
  'Khoya Oal Payasam',
  'Khoya Ol Payasam',
];
